AWSTemplateFormatVersion: 2010-09-09
Description: Autoscale Kinesis Shards using Lambda functions, SNS and Cloudwatch Metric Alarms
Parameters:
  ScaleUpKinesisModuleName:
    Description: The name of the jar
    Type: String
    Default: com.aws.ScaleUpKinesisShards
  ScaleDownKinesisModuleName:
    Description: The name of the jar
    Type: String
    Default: com.aws.ScaleDownKinesisShards
  ScaleUpKinesisS3Key:
    Description: The name of the ZIP package
    Type: String
    Default: scale-kinesis-shards-1.0-SNAPSHOT.jar
  S3Bucket:
    Description: The name of the ZIP package
    Type: String
    Default: tayo-autoscale-kinesis
  ScaleUpMultiplier:
    Description: Scale Up Multiplier
    Type: String
    Default: 2
  ScaleDownMultiplier:
    Description: Scale Down Multiplier
    Type: String
    Default: 0.5d
  MetricName:
    Description: Name of Metric to Alarm on
    Type: String
    Default: IncomingRecords
  Statistic:
    Description: The statistic for the metric associated with the alarm
    Type: String
    Default: Sum
  EvaluationPeriods:
    Description: Number of Evaluation periods before alarm
    Type: Number
    Default: 2
  ScaleUpAlarmThreshold:
    Description: Scale Up Threshold at which alarm should blare
    Type: Number
    Default: 210000
  ScaleDownAlarmThreshold:
    Description: Scale Down Threshold at which alarm should blare
    Type: Number
    Default: 1050000
  Period:
    Description: Period in seconds of Metric Alarm
    Type: Number
    Default: 300
  StreamName:
    Description: Name of Kinesis Stream to scale its shards
    Type: String
    Default: DowIndexStream
  SecurityGroupIds:
    Description: Security Group Ids of the VPC
    Type: AWS::EC2::SecurityGroup::Id
    Default: sg-0333247e
  SubnetIds:
    Description: Subnet Ids of the VPC
    Type: AWS::EC2::Subnet::Id
    Default: "subnet-73e18d3b"
Resources:
  ScaleUpKinesisShards:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref ScaleUpKinesisS3Key
      Handler: !Join
      - ''
      - - !Ref ScaleUpKinesisModuleName
        - ::handleRequest
      Role:
        Fn::GetAtt:
        - "LambdaExecutionRole"
        - "Arn"
      Runtime: java8
      Timeout: '45'
      Tags:
      - Key: Name
        Value: ScaleUpKinesisShard
      Environment:
        Variables:
          scale_up_multiplier: !Ref ScaleUpMultiplier
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroupIds
        SubnetIds:
          - !Ref SubnetIds

  ScaleDownKinesisShards:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref ScaleUpKinesisS3Key
      Handler: !Join
      - ''
      - - !Ref ScaleDownKinesisModuleName
        - ::handleRequest
      Role:
        Fn::GetAtt:
        - "LambdaExecutionRole"
        - "Arn"
      Runtime: java8
      Timeout: '45'
      Tags:
      - Key: Name
        Value: ScaleUpKinesisShard
      Environment:
        Variables:
          scale_down_multiplier: !Ref ScaleDownMultiplier
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroupIds
        SubnetIds:
          - !Ref SubnetIds

  SNSTopic:
    Type: 'AWS::SNS::Topic'
    Properties: {}
  SNSSubscription:
    Type: 'AWS::SNS::Subscription'
    Properties:
      Endpoint:
        Fn::GetAtt:
        - "ScaleUpKinesisShards"
        - "Arn"
      Protocol: "lambda"
      TopicArn: !Ref SNSTopic

  ScaleUpAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: !Join
      - ''
      - - !Ref ScaleUpAlarmThreshold
        - "Alarm if over"
      Namespace: AWS/Kineis
      MetricName: !Ref MetricName
      Dimensions:
      - Name: StreamName
        Value: !Ref StreamName
      Statistic: !Ref Statistic
      Period: !Ref Period
      EvaluationPeriods: !Ref EvaluationPeriods
      Threshold: !Ref ScaleUpAlarmThreshold
      ComparisonOperator: GreaterThanOrEqualToThreshold
      AlarmActions:
      - Ref: SNSTopic
      InsufficientDataActions:
      - Ref: SNSTopic

  ScaleDownAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: !Join
      - ''
      - - !Ref ScaleDownAlarmThreshold
        - "Alarm if over"
      Namespace: AWS/Kineis
      MetricName: !Ref MetricName
      Dimensions:
      - Name: StreamName
        Value: !Ref StreamName
      Statistic: !Ref Statistic
      Period: !Ref Period
      EvaluationPeriods: !Ref EvaluationPeriods
      Threshold: !Ref ScaleDownAlarmThreshold
      ComparisonOperator: LessThanOrEqualToThreshold
      AlarmActions:
      - Ref: SNSTopic
      InsufficientDataActions:
      - Ref: SNSTopic

  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'Auto-Scale-Kinesis-Lambda-Execution-Role'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - 'lambda.amazonaws.com'
          Action: 'sts:AssumeRole'
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/AmazonKinesisFullAccess'
      - 'arn:aws:iam::aws:policy/CloudwatchFullAccess'
      - 'arn:aws:iam::aws:policy/AmazonSNSFullAccess'
      - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
      - 'arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole'
